name: CI
on:
  push:
    paths-ignore:
      - README.md
      - '.github/workflows/github-pages.yml'
      - '.github/workflows/release.yml'
    branches:
      - master
  pull_request:
    paths-ignore:
      - README.md
      - '.github/workflows/github-pages.yml'
    branches:
      - master

env:
  CARGO_TERM_COLOR: always
  PYTHONUNBUFFERED: 1

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install toml
        run: pip3 install toml
      - name: Check
        run: python check_features.py